services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - my-network

  api:
    image: node:18
    container_name: mock-api
    working_dir: /app
    volumes:
      - ./public/data.json:/app/data.json
    command: npx json-server --watch data.json --port 3001
    ports:
      - "3001:3001"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
